const dateInput = document.getElementById('publish-date');
dateInput.value = new Date().toISOString().slice(0, 10);

async function request(url, options) { const response = await fetch(url, options); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || '请求失败'); return data; }
async function verifyAdmin() { try { const { user } = await request('api/auth/me'); if (!user || user.role !== 'admin') throw new Error(); document.getElementById('admin-email').textContent = user.email; } catch { window.location.replace('index.html'); } }
function showFiles() { const files = [...document.getElementById('file-input').files]; document.getElementById('file-count').textContent = files.length ? `已选择 ${files.length} 个文件` : '尚未选择文件'; document.getElementById('file-list').innerHTML = files.slice(0, 12).map(file => `<span>${file.name}</span>`).join('') + (files.length > 12 ? `<span>还有 ${files.length - 12} 篇</span>` : ''); }
async function loadStories() { const target = document.getElementById('story-list'); target.textContent = '正在读取…'; try { const { stories } = await request('api/admin/stories'); target.innerHTML = stories.length ? stories.map(story => `<article class="story"><time>${story.publish_date}</time><div><strong>${story.title}</strong><span> · ${story.author} · ${story.tag}</span></div><span>${story.minutes} 分钟</span><button data-delete="${story.id}">下架</button></article>`).join('') : '<p>还没有通过后台发布的小说。</p>'; } catch (error) { target.textContent = error.message; } }
document.getElementById('file-input').addEventListener('change', showFiles);
document.getElementById('publish-form').addEventListener('submit', async event => { event.preventDefault(); const message = document.getElementById('publish-message'); const files = [...document.getElementById('file-input').files]; if (!files.length) return; message.textContent = '正在读取并发布…'; try { const payload = { date: dateInput.value, files: await Promise.all(files.map(async file => ({ name:file.name, text:await file.text() }))) }; const result = await request('api/admin/stories', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify(payload) }); message.textContent = `已发布 ${result.count} 篇小说。`; event.target.reset(); showFiles(); await loadStories(); } catch (error) { message.textContent = error.message; } });
document.getElementById('story-list').addEventListener('click', async event => { const button = event.target.closest('[data-delete]'); if (!button || !confirm('确认下架这篇小说？')) return; try { await request(`api/admin/stories/${button.dataset.delete}`, {method:'DELETE'}); await loadStories(); } catch (error) { alert(error.message); } });
document.getElementById('refresh-button').addEventListener('click', loadStories);
document.getElementById('logout-button').addEventListener('click', async () => { await request('api/auth/logout', {method:'POST'}).catch(() => null); window.location.replace('index.html'); });
verifyAdmin(); loadStories();
